"""initial marketplace tables

Revision ID: e18509a42d04
Revises:
Create Date: 2026-08-25 00:25:18.882250
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "e18509a42d04"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("role", sa.Enum("farmer", "buyer", "admin", name="user_role", native_enum=False), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "subscription_status",
            sa.Enum("none", "active", "expired", name="subscription_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_phone_number"), "users", ["phone_number"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_subscription_status"), "users", ["subscription_status"], unique=False)
    op.create_table(
        "buyer_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("business_name", sa.String(length=120), nullable=True),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "farmer_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("district", sa.String(length=120), nullable=True),
        sa.Column("preferred_language", sa.String(length=20), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("farmer_id", sa.Integer(), nullable=False),
        sa.Column("crop", sa.String(length=80), nullable=False),
        sa.Column("quantity_kg", sa.Float(), nullable=False),
        sa.Column("price_per_kg", sa.Float(), nullable=True),
        sa.Column("harvest_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "sold", "expired", "cancelled", name="listing_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price_per_kg IS NULL OR price_per_kg >= 0", name="ck_listing_price_non_negative"),
        sa.CheckConstraint("quantity_kg > 0", name="ck_listing_quantity_positive"),
        sa.ForeignKeyConstraint(["farmer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_listings_farmer_id", "listings", ["farmer_id"], unique=False)
    op.create_index("ix_listings_status_crop", "listings", ["status", "crop"], unique=False)
    op.create_table(
        "connection_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "declined", "completed", name="connection_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["buyer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_connection_buyer_id", "connection_requests", ["buyer_id"], unique=False)
    op.create_index("ix_connection_listing_id", "connection_requests", ["listing_id"], unique=False)
    op.create_index(
        "ux_connection_requests_pending",
        "connection_requests",
        ["listing_id", "buyer_id"],
        unique=True,
        sqlite_where=sa.text("status = 'pending'"),
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_connection_requests_pending",
        table_name="connection_requests",
        sqlite_where=sa.text("status = 'pending'"),
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index("ix_connection_listing_id", table_name="connection_requests")
    op.drop_index("ix_connection_buyer_id", table_name="connection_requests")
    op.drop_table("connection_requests")
    op.drop_index("ix_listings_status_crop", table_name="listings")
    op.drop_index("ix_listings_farmer_id", table_name="listings")
    op.drop_table("listings")
    op.drop_table("farmer_profiles")
    op.drop_table("buyer_profiles")
    op.drop_index(op.f("ix_users_subscription_status"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
